name: Selenium Java Test with Allure Report

on:
  push:
    branches: [main]
  pull_request:

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build frontend Docker image
        run: docker build -t demo-site frontend

      - name: Run frontend container
        run: docker run -d -p 8080:80 --name demo-site demo-site

      - name: Wait for frontend to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/login.html | grep -q "<title>"; then
              echo "Frontend is ready."
              break
            fi
            echo "Waiting for frontend to be ready..."
            sleep 2
          done

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl gnupg unzip
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install matching ChromeDriver
        run: |
          BASE_URL="https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json"
          DRIVER_URL=$(curl -s $BASE_URL | jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -O chromedriver.zip "$DRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium tests with Maven
        run: cd tests && mvn clean test

      # Generate Allure report
      - name: Generate Allure Report
        run: cd tests && mvn allure:report

      # Upload Allure report as an artifact, for manual download if needed
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: tests/target/site/allure-maven-plugin

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tests/target/site/allure-maven-plugin
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
